# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/robbe/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/212.5457.51/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/robbe/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/212.5457.51/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/robbe/Desktop/master-thesis-robbe-louwet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/robbe/Desktop/master-thesis-robbe-louwet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/robbe/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/212.5457.51/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/robbe/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/212.5457.51/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robbe/Desktop/master-thesis-robbe-louwet/CMakeFiles /home/robbe/Desktop/master-thesis-robbe-louwet//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robbe/Desktop/master-thesis-robbe-louwet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named forkskinnyplus

# Build rule for target.
forkskinnyplus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 forkskinnyplus
.PHONY : forkskinnyplus

# fast build rule for target.
forkskinnyplus/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/forkskinnyplus.dir/build.make CMakeFiles/forkskinnyplus.dir/build
.PHONY : forkskinnyplus/fast

#=============================================================================
# Target rules for targets named skinny-plus

# Build rule for target.
skinny-plus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 skinny-plus
.PHONY : skinny-plus

# fast build rule for target.
skinny-plus/fast:
	$(MAKE) $(MAKESILENT) -f contrib/skinny-plus/CMakeFiles/skinny-plus.dir/build.make contrib/skinny-plus/CMakeFiles/skinny-plus.dir/build
.PHONY : skinny-plus/fast

contrib/forkskinny-c/forkskinny128-cipher.o: contrib/forkskinny-c/forkskinny128-cipher.c.o
.PHONY : contrib/forkskinny-c/forkskinny128-cipher.o

# target to build an object file
contrib/forkskinny-c/forkskinny128-cipher.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/forkskinnyplus.dir/build.make CMakeFiles/forkskinnyplus.dir/contrib/forkskinny-c/forkskinny128-cipher.c.o
.PHONY : contrib/forkskinny-c/forkskinny128-cipher.c.o

contrib/forkskinny-c/forkskinny128-cipher.i: contrib/forkskinny-c/forkskinny128-cipher.c.i
.PHONY : contrib/forkskinny-c/forkskinny128-cipher.i

# target to preprocess a source file
contrib/forkskinny-c/forkskinny128-cipher.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/forkskinnyplus.dir/build.make CMakeFiles/forkskinnyplus.dir/contrib/forkskinny-c/forkskinny128-cipher.c.i
.PHONY : contrib/forkskinny-c/forkskinny128-cipher.c.i

contrib/forkskinny-c/forkskinny128-cipher.s: contrib/forkskinny-c/forkskinny128-cipher.c.s
.PHONY : contrib/forkskinny-c/forkskinny128-cipher.s

# target to generate assembly for a file
contrib/forkskinny-c/forkskinny128-cipher.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/forkskinnyplus.dir/build.make CMakeFiles/forkskinnyplus.dir/contrib/forkskinny-c/forkskinny128-cipher.c.s
.PHONY : contrib/forkskinny-c/forkskinny128-cipher.c.s

contrib/forkskinny-c/forkskinny64-cipher.o: contrib/forkskinny-c/forkskinny64-cipher.c.o
.PHONY : contrib/forkskinny-c/forkskinny64-cipher.o

# target to build an object file
contrib/forkskinny-c/forkskinny64-cipher.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/forkskinnyplus.dir/build.make CMakeFiles/forkskinnyplus.dir/contrib/forkskinny-c/forkskinny64-cipher.c.o
.PHONY : contrib/forkskinny-c/forkskinny64-cipher.c.o

contrib/forkskinny-c/forkskinny64-cipher.i: contrib/forkskinny-c/forkskinny64-cipher.c.i
.PHONY : contrib/forkskinny-c/forkskinny64-cipher.i

# target to preprocess a source file
contrib/forkskinny-c/forkskinny64-cipher.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/forkskinnyplus.dir/build.make CMakeFiles/forkskinnyplus.dir/contrib/forkskinny-c/forkskinny64-cipher.c.i
.PHONY : contrib/forkskinny-c/forkskinny64-cipher.c.i

contrib/forkskinny-c/forkskinny64-cipher.s: contrib/forkskinny-c/forkskinny64-cipher.c.s
.PHONY : contrib/forkskinny-c/forkskinny64-cipher.s

# target to generate assembly for a file
contrib/forkskinny-c/forkskinny64-cipher.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/forkskinnyplus.dir/build.make CMakeFiles/forkskinnyplus.dir/contrib/forkskinny-c/forkskinny64-cipher.c.s
.PHONY : contrib/forkskinny-c/forkskinny64-cipher.c.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/forkskinnyplus.dir/build.make CMakeFiles/forkskinnyplus.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/forkskinnyplus.dir/build.make CMakeFiles/forkskinnyplus.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/forkskinnyplus.dir/build.make CMakeFiles/forkskinnyplus.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... forkskinnyplus"
	@echo "... skinny-plus"
	@echo "... contrib/forkskinny-c/forkskinny128-cipher.o"
	@echo "... contrib/forkskinny-c/forkskinny128-cipher.i"
	@echo "... contrib/forkskinny-c/forkskinny128-cipher.s"
	@echo "... contrib/forkskinny-c/forkskinny64-cipher.o"
	@echo "... contrib/forkskinny-c/forkskinny64-cipher.i"
	@echo "... contrib/forkskinny-c/forkskinny64-cipher.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

