#ifndef FORKSKINNYPLUS_MAIN_H
#define FORKSKINNYPLUS_MAIN_H

#include <cstdint>
#include "forkskinny-c/headers/forkskinny64-cipher.h"
#include "forkskinny-c/headers/forkskinny-internal.h"

STATIC_INLINE void skinny64_permute_tk(State64_t *tk) {
	/* PT = [9, 15, 8, 13, 10, 14, 12, 11, 0, 1, 2, 3, 4, 5, 6, 7] */
	#if SKINNY_LITTLE_ENDIAN
	/* Permutation generated by http://programming.sirrida.de/calcperm.php */
	uint32_t x = tk->lrow[1];
	tk->lrow[1] = tk->lrow[0];
	tk->lrow[0] = ((x & 0x0000000FU) << 4) |
	              ((x & 0x00F0F0F0U) << 8) |
	              ((x & 0x0F000000U) >> 24) |
	              ((x & 0x00000F00U) << 16) |
	              ((x & 0xF0000000U) >> 12) |
	              ((x & 0x000F0000U) >> 8);
	#else
	uint16_t row2 = tk->row[2];
	uint16_t row3 = tk->row[3];
	tk->row[2] = tk->row[0];
	tk->row[3] = tk->row[1];
	row3 = (row3 << 8) | (row3 >> 8);
	tk->row[0] = ((row2 << 4) & 0x00F0U) |
	             ((row2 << 8) & 0xF000U) |
	             (row3       & 0x0F0FU);
	tk->row[1] = ((row2 >> 8) & 0x00F0U) |
	             (row2       & 0x0F00U) |
	             ((row3 >> 4) & 0x000FU) |
	             ( row3       & 0xF000U);
	#endif
}
#endif //FORKSKINNYPLUS_MAIN_H
